"use client";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";
import { attemptExam, getExam } from "@/services/examService";
import { Question } from "@/types/questions";
import {
  Exam,
  ExamAttempt,
  ExamAttemptResponse,
  ExamAttemptSchema,
} from "@/types/exams";
import { zodResolver } from "@hookform/resolvers/zod";
import { Book } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import {
  FormProvider,
  SubmitHandler,
  useForm,
  useFormContext,
} from "react-hook-form";
import { toast } from "sonner";
import { QuestionComponent } from "./_components/questionComponent/page";

// export const metadata: Metadata = {
//   title: "Simulados",
//   description: "Generated by create next app",
// };

export default function Dashboard() {
  const router = useRouter();
  const [exam, setExam] = useState<Exam | null>(null);
  const [loading, setLoading] = useState(true);
  const searchParams = useSearchParams();
  const id = searchParams.get("id");

  const form = useForm<ExamAttempt>({
    resolver: zodResolver(ExamAttemptSchema),
    defaultValues: {
      examId: Number(id),
    },
  });

  // form.setValue("examId", Number(id));

  const { handleSubmit, reset } = form;
  const handleExamAttempt: SubmitHandler<ExamAttempt> = async (data) => {
    console.log("Form Data:", data);
    attemptExam(Number(id), data.answers).then((response) => {
      if (response as ExamAttemptResponse) {
        toast("Tentativa de simulado enviada.");
        console.log("Response de tentativa de simulado:", response);
        reset();
        router.push(`/dashboard/tentativas/${response.id}`);
      } else {
        toast("Erro ao enviar tentativa de simulado.");
      }
      console.log("Response:", response);
    });
  };

  useEffect(() => {
    if (id !== null) {
      getExam(Number(id))
        .then((data: Exam) => {
          console.log("buscou os exames", data);
          console.log("questions:", data.questions);
          setExam(data);
          setLoading(false);
        })
        .catch((error) => {
          setLoading(false);
        });
    }
  }, [id]);

  if (loading) {
    return <div>Loading...</div>;
  }

  if (!exam) {
    return <div>No exam found</div>;
  }

  return (
    <FormProvider {...form}>
      <form onSubmit={handleSubmit(handleExamAttempt)}>
        <div className="flex flex-col sm:gap-4 sm:py-4 w-full">
          <div className="px-2 py-4">
            <div className="flex space-x-1">
              <div className="flex items-center">
                <Book className="h-6 w-6" />
              </div>
              <h1 className="scroll-m-20 text-3xl font-semibold tracking-tight first:mt-0 capitalize">
                {exam.name}
              </h1>
            </div>
            <div className="my-1">
              <div className="flex space-x-2">
                <h4 className="font-semibold scroll-m-20">Categoria</h4>
                <div className="text-muted-foreground">{exam.examType}</div>
              </div>

              {exam.discipline && (
                <div className="flex space-x-2">
                  <h4 className="font-semibold scroll-m-20">Disciplina</h4>
                  <p className="text-muted-foreground capitalize">
                    {exam.discipline.name}
                  </p>
                </div>
              )}
              {exam.topic && (
                <div className="flex space-x-2">
                  <h4 className="font-semibold scroll-m-20">Tópico</h4>
                  <p className="text-muted-foreground capitalize">
                    {exam.topic.name}
                  </p>
                </div>
              )}
              {exam.year && (
                <div className="flex">
                  <h4 className="font-semibold scroll-m-20">Ano</h4>
                  <p className="pl-2 text-muted-foreground">{exam.year}</p>
                </div>
              )}
              <div className="flex my-2 space-x-2">
                <h4 className="font-semibold scroll-m-20">Tags</h4>
                {exam.tags?.map((tag) => {
                  return (
                    <Badge variant={"outline"} key={tag}>
                      {tag}
                    </Badge>
                  );
                })}
              </div>
            </div>
          </div>
          <main className="grid flex-1 items-start gap-4 sm:px-6 sm:py-0 md:gap-8 lg:grid-cols-1 xl:grid-cols-1 w-full px-2">
            <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight mt-2">
              Questões
            </h3>
            {exam.questions.map((question: Question, index: number) => (
              <QuestionComponent
                key={question.id}
                question={question}
                index={index}
              />
            ))}
            <div>
              <PaginationComponent />
            </div>
            <div className="flex justify-end space-x-2 my-2">
              <Button variant={"outline"}>Salvar Rascunho</Button>
              <Button type="submit" disabled={loading}>
                Enviar
              </Button>
            </div>
          </main>
        </div>
        <FormErrors />
      </form>
    </FormProvider>
  );
}

export function ExamDetails({ exam }: { exam: Exam }) {
  return (
    <div className="px-2 py-4">
      <div className="flex space-x-1">
        <div className="flex items-center">
          <Book className="h-6 w-6" />
        </div>
        <h1 className="scroll-m-20 text-3xl font-semibold tracking-tight first:mt-0 capitalize">
          {exam.name}
        </h1>
      </div>
      <div className="my-1">
        <div className="flex space-x-2">
          <h4 className="font-semibold scroll-m-20">Categoria</h4>
          <div className="text-muted-foreground">{exam.examType}</div>
        </div>

        {exam.discipline && (
          <div className="flex space-x-2">
            <h4 className="font-semibold scroll-m-20">Disciplina</h4>
            <p className="text-muted-foreground capitalize">
              {exam.discipline.name}
            </p>
          </div>
        )}
        {exam.topic && (
          <div className="flex space-x-2">
            <h4 className="font-semibold scroll-m-20">Tópico</h4>
            <p className="text-muted-foreground capitalize">
              {exam.topic.name}
            </p>
          </div>
        )}
        {exam.year && (
          <div className="flex">
            <h4 className="font-semibold scroll-m-20">Ano</h4>
            <p className="pl-2 text-muted-foreground">{exam.year}</p>
          </div>
        )}
        <div className="flex my-2 space-x-2">
          <h4 className="font-semibold scroll-m-20">Tags</h4>
          {exam.tags?.map((tag) => {
            return (
              <Badge variant={"outline"} key={tag}>
                {tag}
              </Badge>
            );
          })}
        </div>
      </div>
    </div>
  );
}

const PaginationComponent = () => {
  return (
    <Pagination>
      <PaginationContent>
        <PaginationItem>
          <PaginationPrevious href="#" />
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#" isActive>
            1
          </PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#">2</PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#">3</PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationEllipsis />
        </PaginationItem>
        <PaginationItem>
          <PaginationNext href="#" />
        </PaginationItem>
      </PaginationContent>
    </Pagination>
  );
};

const FormErrors: React.FC = () => {
  const {
    formState: { errors },
  } = useFormContext<ExamAttempt>();

  return (
    <div className="text-red-500">
      {Object.keys(errors).map((field) => (
        <div key={field}>
          {field}: {errors[field as keyof typeof errors]?.message}
        </div>
      ))}
    </div>
  );
};
