import { Question } from "./attempts";
import { ExamTypeEnum } from "./common";

export const questions: Question[] = [
  {
    id: 0,
    statement:
      "A economia das possessões coloniais portuguesas na América foi marcada por mercadorias que, uma vez exportadas para outras regiões do mundo, podiam alcançar alto valor e garantir, aos envolvidos em seu comércio, grandes lucros. Além do açúcar, explorado desde meados do século XVI, e do ouro, extraído regularmente desde fins do XVII, merecem destaque, como elementos de exportação presentes nessa economia:",
    explanation: "Explicação da questão",
    difficulty: "EASY",
    examType: ExamTypeEnum.Enum.ENADE,
    discipline: {
      id: "1",
      name: "História",
    },
    topic: "Período Colonial",
    year: 2021,
    source: "FUVEST",
    sourceUrl: "https://fuvest.br",
    authorId: "1",
    tags: ["matemática", "álgebra"],
    comments: [],
    alternatives: [
      {
        id: "1",
        label: "A",
        text: "tabaco, algodão e derivados da pecuária.",
      },
      {
        id: "2",
        label: "B",
        text: "ferro, sal e tecidos.",
      },
      {
        id: "3",
        label: "C",
        text: "escravos indígenas, arroz e diamantes.",
      },
      {
        id: "4",
        label: "D",
        text: "animais exóticos, cacau e embarcações.",
      },
      {
        id: "5",
        label: "E",
        text: "drogas do sertão, frutos do mar e cordoaria.",
      },
    ],
    correctAlternative: "A",
  },
  {
    id: 1,
    statement: "A escravidão na Roma antiga",
    explanation: "Explicação da questão",
    difficulty: "MEDIUM",
    examType: ExamTypeEnum.Enum.ENADE,
    discipline: {
      id: "1",
      name: "Matemática",
    },
    topic: "Álgebra",
    year: 2021,
    source: "FUVEST",
    sourceUrl: "https://fuvest.br",
    authorId: "1",
    tags: ["matemática", "álgebra"],
    comments: [],
    alternatives: [
      {
        id: "1",
        label: "A",
        text: "permaneceu praticamente inalterada ao longo dos séculos, mas foi abolida com a introdução do cristianismo.",
      },
      {
        id: "2",
        label: "B",
        text: "previa a possibilidade de alforria do escravo apenas no caso da morte de seu proprietário.",
      },
      {
        id: "3",
        label: "C",
        text: "era restrita ao meio rural e associada ao trabalho braçal, não ocorrendo em áreas urbanas, nem atingindo funções intelectuais ou administrativas.",
      },
      {
        id: "4",
        label: "D",
        text: "pressupunha que os escravos eram humanos e, por isso, era proibida toda forma de castigo físico.",
      },
      {
        id: "5",
        label: "E",
        text: "variou ao longo do tempo, mas era determinada por três critérios: nascimento, guerra e direito civil.",
      },
    ],
    correctAlternative: "A",
  },
  {
    id: 2,
    statement: "Questão de exemplo 2",
    explanation: "Explicação da questão 2",
    difficulty: "HARD",
    examType: ExamTypeEnum.Enum.ENEM,
    discipline: {
      id: "2",
      name: "Português",
    },
    topic: "Interpretação de texto",
    year: 2021,
    source: "ENEM",
    sourceUrl: "https://enem.inep.gov.br",
    authorId: "2",
    tags: ["português", "interpretação"],
    comments: [],
    alternatives: [
      {
        id: "1",
        label: "A",
        text: "Alternativa A",
      },
      {
        id: "2",
        label: "B",
        text: "Alternativa B",
      },
      {
        id: "3",
        label: "C",
        text: "Alternativa C",
      },
      {
        id: "4",
        label: "D",
        text: "Alternativa D",
      },
    ],
    correctAlternative: "B",
  },
  {
    id: 3,
    statement: "Questão de exemplo 2",
    explanation: "Explicação da questão 2",
    difficulty: "MEDIUM",
    examType: ExamTypeEnum.Enum.ENEM,
    discipline: {
      id: "2",
      name: "Português",
    },
    topic: "Interpretação de texto",
    year: 2021,
    source: "ENEM",
    sourceUrl: "https://enem.inep.gov.br",
    authorId: "2",
    tags: ["português", "interpretação"],
    comments: [],
    alternatives: [
      {
        id: "1",
        label: "A",
        text: "Alternativa A",
      },
      {
        id: "2",
        label: "B",
        text: "Alternativa B",
      },
      {
        id: "3",
        label: "C",
        text: "Alternativa C",
      },
      {
        id: "4",
        label: "D",
        text: "Alternativa D",
      },
    ],
    correctAlternative: "B",
  },
  {
    id: 4,
    statement:
      "A economia das possessões coloniais portuguesas na América foi marcada por mercadorias que, uma vez exportadas para outras regiões do mundo, podiam alcançar alto valor e garantir, aos envolvidos em seu comércio, grandes lucros. Além do açúcar, explorado desde meados do século XVI, e do ouro, extraído regularmente desde fins do XVII, merecem destaque, como elementos de exportação presentes nessa economia:",
    explanation: "Explicação da questão",
    difficulty: "EASY",
    examType: ExamTypeEnum.Enum.ENADE,
    discipline: {
      id: "1",
      name: "História",
    },
    topic: "Período Colonial",
    year: 2021,
    source: "FUVEST",
    sourceUrl: "https://fuvest.br",
    authorId: "1",
    tags: ["matemática", "álgebra"],
    comments: [],
    alternatives: [
      {
        id: "1",
        label: "A",
        text: "tabaco, algodão e derivados da pecuária.",
      },
      {
        id: "2",
        label: "B",
        text: "ferro, sal e tecidos.",
      },
      {
        id: "3",
        label: "C",
        text: "escravos indígenas, arroz e diamantes.",
      },
      {
        id: "4",
        label: "D",
        text: "animais exóticos, cacau e embarcações.",
      },
      {
        id: "5",
        label: "E",
        text: "drogas do sertão, frutos do mar e cordoaria.",
      },
    ],
    correctAlternative: "A",
  },
  {
    id: 5,
    statement: "A escravidão na Roma antiga",
    explanation: "Explicação da questão",
    difficulty: "MEDIUM",
    examType: ExamTypeEnum.Enum.ENADE,
    discipline: {
      id: "1",
      name: "Matemática",
    },
    topic: "Álgebra",
    year: 2021,
    source: "FUVEST",
    sourceUrl: "https://fuvest.br",
    authorId: "1",
    tags: ["matemática", "álgebra"],
    comments: [],
    alternatives: [
      {
        id: "1",
        label: "A",
        text: "permaneceu praticamente inalterada ao longo dos séculos, mas foi abolida com a introdução do cristianismo.",
      },
      {
        id: "2",
        label: "B",
        text: "previa a possibilidade de alforria do escravo apenas no caso da morte de seu proprietário.",
      },
      {
        id: "3",
        label: "C",
        text: "era restrita ao meio rural e associada ao trabalho braçal, não ocorrendo em áreas urbanas, nem atingindo funções intelectuais ou administrativas.",
      },
      {
        id: "4",
        label: "D",
        text: "pressupunha que os escravos eram humanos e, por isso, era proibida toda forma de castigo físico.",
      },
      {
        id: "5",
        label: "E",
        text: "variou ao longo do tempo, mas era determinada por três critérios: nascimento, guerra e direito civil.",
      },
    ],
    correctAlternative: "A",
  },
  {
    id: 6,
    statement: "Questão de exemplo 2",
    explanation: "Explicação da questão 2",
    difficulty: "HARD",
    examType: ExamTypeEnum.Enum.ENEM,
    discipline: {
      id: "2",
      name: "Português",
    },
    topic: "Interpretação de texto",
    year: 2021,
    source: "ENEM",
    sourceUrl: "https://enem.inep.gov.br",
    authorId: "2",
    tags: ["português", "interpretação"],
    comments: [],
    alternatives: [
      {
        id: "1",
        label: "A",
        text: "Alternativa A",
      },
      {
        id: "2",
        label: "B",
        text: "Alternativa B",
      },
      {
        id: "3",
        label: "C",
        text: "Alternativa C",
      },
      {
        id: "4",
        label: "D",
        text: "Alternativa D",
      },
    ],
    correctAlternative: "B",
  },
  {
    id: 7,
    statement: "Questão de exemplo 2",
    explanation: "Explicação da questão 2",
    difficulty: "MEDIUM",
    examType: ExamTypeEnum.Enum.ENEM,
    discipline: {
      id: "2",
      name: "Português",
    },
    topic: "Interpretação de texto",
    year: 2021,
    source: "ENEM",
    sourceUrl: "https://enem.inep.gov.br",
    authorId: "2",
    tags: ["português", "interpretação"],
    comments: [],
    alternatives: [
      {
        id: "1",
        label: "A",
        text: "Alternativa A",
      },
      {
        id: "2",
        label: "B",
        text: "Alternativa B",
      },
      {
        id: "3",
        label: "C",
        text: "Alternativa C",
      },
      {
        id: "4",
        label: "D",
        text: "Alternativa D",
      },
    ],
    correctAlternative: "B",
  },
  {
    id: 8,
    statement:
      "A economia das possessões coloniais portuguesas na América foi marcada por mercadorias que, uma vez exportadas para outras regiões do mundo, podiam alcançar alto valor e garantir, aos envolvidos em seu comércio, grandes lucros. Além do açúcar, explorado desde meados do século XVI, e do ouro, extraído regularmente desde fins do XVII, merecem destaque, como elementos de exportação presentes nessa economia:",
    explanation: "Explicação da questão",
    difficulty: "EASY",
    examType: ExamTypeEnum.Enum.ENADE,
    discipline: {
      id: "1",
      name: "História",
    },
    topic: "Período Colonial",
    year: 2021,
    source: "FUVEST",
    sourceUrl: "https://fuvest.br",
    authorId: "1",
    tags: ["matemática", "álgebra"],
    comments: [],
    alternatives: [
      {
        id: "1",
        label: "A",
        text: "tabaco, algodão e derivados da pecuária.",
      },
      {
        id: "2",
        label: "B",
        text: "ferro, sal e tecidos.",
      },
      {
        id: "3",
        label: "C",
        text: "escravos indígenas, arroz e diamantes.",
      },
      {
        id: "4",
        label: "D",
        text: "animais exóticos, cacau e embarcações.",
      },
      {
        id: "5",
        label: "E",
        text: "drogas do sertão, frutos do mar e cordoaria.",
      },
    ],
    correctAlternative: "A",
  },
  {
    id: 9,
    statement: "A escravidão na Roma antiga",
    explanation: "Explicação da questão",
    difficulty: "MEDIUM",
    examType: ExamTypeEnum.Enum.ENADE,
    discipline: {
      id: "1",
      name: "Matemática",
    },
    topic: "Álgebra",
    year: 2021,
    source: "FUVEST",
    sourceUrl: "https://fuvest.br",
    authorId: "1",
    tags: ["matemática", "álgebra"],
    comments: [],
    alternatives: [
      {
        id: "1",
        label: "A",
        text: "permaneceu praticamente inalterada ao longo dos séculos, mas foi abolida com a introdução do cristianismo.",
      },
      {
        id: "2",
        label: "B",
        text: "previa a possibilidade de alforria do escravo apenas no caso da morte de seu proprietário.",
      },
      {
        id: "3",
        label: "C",
        text: "era restrita ao meio rural e associada ao trabalho braçal, não ocorrendo em áreas urbanas, nem atingindo funções intelectuais ou administrativas.",
      },
      {
        id: "4",
        label: "D",
        text: "pressupunha que os escravos eram humanos e, por isso, era proibida toda forma de castigo físico.",
      },
      {
        id: "5",
        label: "E",
        text: "variou ao longo do tempo, mas era determinada por três critérios: nascimento, guerra e direito civil.",
      },
    ],
    correctAlternative: "A",
  },
  {
    id: 10,
    statement: "Questão de exemplo 2",
    explanation: "Explicação da questão 2",
    difficulty: "HARD",
    examType: ExamTypeEnum.Enum.ENEM,
    discipline: {
      id: "2",
      name: "Português",
    },
    topic: "Interpretação de texto",
    year: 2021,
    source: "ENEM",
    sourceUrl: "https://enem.inep.gov.br",
    authorId: "2",
    tags: ["português", "interpretação"],
    comments: [],
    alternatives: [
      {
        id: "1",
        label: "A",
        text: "Alternativa A",
      },
      {
        id: "2",
        label: "B",
        text: "Alternativa B",
      },
      {
        id: "3",
        label: "C",
        text: "Alternativa C",
      },
      {
        id: "4",
        label: "D",
        text: "Alternativa D",
      },
    ],
    correctAlternative: "B",
  },
  {
    id: 11,
    statement: "Questão de exemplo 2",
    explanation: "Explicação da questão 2",
    difficulty: "MEDIUM",
    examType: ExamTypeEnum.Enum.ENEM,
    discipline: {
      id: "2",
      name: "Português",
    },
    topic: "Interpretação de texto",
    year: 2021,
    source: "ENEM",
    sourceUrl: "https://enem.inep.gov.br",
    authorId: "2",
    tags: ["português", "interpretação"],
    comments: [],
    alternatives: [
      {
        id: "1",
        label: "A",
        text: "Alternativa A",
      },
      {
        id: "2",
        label: "B",
        text: "Alternativa B",
      },
      {
        id: "3",
        label: "C",
        text: "Alternativa C",
      },
      {
        id: "4",
        label: "D",
        text: "Alternativa D",
      },
    ],
    correctAlternative: "B",
  },
];
