import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AppSidebar } from "@/components/sidebar/app-sidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { Breadcrumbs } from "@/components/sidebar/breadcrumb";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Simulados",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { cookies } = await import("next/headers");
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider
          defaultOpen={cookies().get("sidebar:state")?.value === "true"}
        >
          <AppSidebar />
          <SidebarInset>
            <main className="transition-all duration-300 ease-in-out">
              <div className="sticky top-0 bg-white z-10 p-2">
                <div className="flex items-center gap-2">
                  <SidebarTrigger />
                  <Breadcrumbs />
                </div>
              </div>
              <div className="p-2">{children}</div>
              <Toaster />
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
