import { Metadata } from "next";
import { ExamsTable } from "./_components/examsTable/examsTable";

export const metadata: Metadata = {
  title: "Simulados",
  description: "Generated by create next app",
};

export default function Dashboard() {
  return (
    <div className="flex flex-col sm:gap-4 sm:py-4 w-full">
      <div className="md:px-6 py-2">
        <h2 className="scroll-m-20 text-3xl font-semibold tracking-tight first:mt-0">
          Simulados
        </h2>
        <p className="text-muted-foreground mt-0">
          Crie e adicione questões a simulados
        </p>
      </div>

      <main className="grid flex-1 items-start gap-4 sm:px-6 sm:py-0 md:gap-8 lg:grid-cols-1 xl:grid-cols-1 w-full">
        <ExamsTable />
      </main>
    </div>
  );
}
